package org.example.model;
// Generated Jan 27, 2023, 3:03:53 PM by Hibernate Tools 5.2.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catagory generated by hbm2java
 */
@Entity
@Table(name="catagory"
    ,catalog="librarysys"
)
public class Catagory  implements java.io.Serializable {


     private int id;
     private String catagoryName;
     private Set<Book> books = new HashSet<Book>(0);

    public Catagory() {
    }

	
    public Catagory(int id, String catagoryName) {
        this.id = id;
        this.catagoryName = catagoryName;
    }
    public Catagory(int id, String catagoryName, Set<Book> books) {
       this.id = id;
       this.catagoryName = catagoryName;
       this.books = books;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="catagory_name", nullable=false, length=64)
    public String getCatagoryName() {
        return this.catagoryName;
    }
    
    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catagory")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


