package org.example.model;
// Generated Jan 27, 2023, 3:03:53 PM by Hibernate Tools 5.2.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="librarysys"
)
public class Users  implements java.io.Serializable {


     private int id;
     private Role role;
     private String name;
     private int phoneNumber;
     private Set<Loanedbook> loanedbooks = new HashSet<Loanedbook>(0);

    public Users() {
    }

	
    public Users(int id, Role role, String name, int phoneNumber) {
        this.id = id;
        this.role = role;
        this.name = name;
        this.phoneNumber = phoneNumber;
    }
    public Users(int id, Role role, String name, int phoneNumber, Set<Loanedbook> loanedbooks) {
       this.id = id;
       this.role = role;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.loanedbooks = loanedbooks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone_number", nullable=false)
    public int getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Loanedbook> getLoanedbooks() {
        return this.loanedbooks;
    }
    
    public void setLoanedbooks(Set<Loanedbook> loanedbooks) {
        this.loanedbooks = loanedbooks;
    }




}


